from distutils.core import setup

setup(
    name='TestProject',
    version='',
    packages=['com', 'com.cm', 'com.cm.main', 'env.Lib.distutils', 'env.Lib.encodings', 'env.Lib.importlib',
              'env.Lib.collections', 'env.Lib.site-packages.pip', 'env.Lib.site-packages.pip._vendor',
              'env.Lib.site-packages.pip._vendor.idna', 'env.Lib.site-packages.pip._vendor.pep517',
              'env.Lib.site-packages.pip._vendor.pytoml', 'env.Lib.site-packages.pip._vendor.certifi',
              'env.Lib.site-packages.pip._vendor.chardet', 'env.Lib.site-packages.pip._vendor.chardet.cli',
              'env.Lib.site-packages.pip._vendor.distlib', 'env.Lib.site-packages.pip._vendor.distlib._backport',
              'env.Lib.site-packages.pip._vendor.msgpack', 'env.Lib.site-packages.pip._vendor.urllib3',
              'env.Lib.site-packages.pip._vendor.urllib3.util', 'env.Lib.site-packages.pip._vendor.urllib3.contrib',
              'env.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.Lib.site-packages.pip._vendor.urllib3.packages',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip._vendor.colorama', 'env.Lib.site-packages.pip._vendor.html5lib',
              'env.Lib.site-packages.pip._vendor.html5lib._trie', 'env.Lib.site-packages.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'env.Lib.site-packages.pip._vendor.lockfile',
              'env.Lib.site-packages.pip._vendor.progress', 'env.Lib.site-packages.pip._vendor.requests',
              'env.Lib.site-packages.pip._vendor.packaging', 'env.Lib.site-packages.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip._vendor.cachecontrol.caches', 'env.Lib.site-packages.pip._vendor.webencodings',
              'env.Lib.site-packages.pip._vendor.pkg_resources', 'env.Lib.site-packages.pip._internal',
              'env.Lib.site-packages.pip._internal.cli', 'env.Lib.site-packages.pip._internal.req',
              'env.Lib.site-packages.pip._internal.vcs', 'env.Lib.site-packages.pip._internal.utils',
              'env.Lib.site-packages.pip._internal.models', 'env.Lib.site-packages.pip._internal.commands',
              'env.Lib.site-packages.pip._internal.operations', 'env.Lib.site-packages.PyQt5',
              'env.Lib.site-packages.PyQt5.uic', 'env.Lib.site-packages.PyQt5.uic.Loader',
              'env.Lib.site-packages.PyQt5.uic.port_v2', 'env.Lib.site-packages.PyQt5.uic.port_v3',
              'env.Lib.site-packages.PyQt5.uic.Compiler', 'env.Lib.site-packages.wheel',
              'env.Lib.site-packages.wheel.cli', 'env.Lib.site-packages.setuptools',
              'env.Lib.site-packages.setuptools.extern', 'env.Lib.site-packages.setuptools._vendor',
              'env.Lib.site-packages.setuptools._vendor.packaging', 'env.Lib.site-packages.setuptools.command',
              'env.Lib.site-packages.pkg_resources', 'env.Lib.site-packages.pkg_resources.extern',
              'env.Lib.site-packages.pkg_resources._vendor', 'env.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='hmcho',
    author_email='',
    description=''
)
